{{- /*
# SPDX-License-Identifier: Apache-2.0
# Â© Crown Copyright 2025. This work has been developed by the National Digital Twin Programme and is legally attributed to the Department for Business and Trade (UK) as the governing entity.
*/}}

{{- if .Values.kafkaCluster.secret.create  -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{  .Values.kafkaCluster.secret.usernameConnect }}
  labels:
    strimzi.io/cluster: {{.Values.kafkaCluster.name}}
    strimzi.io/kind: KafkaUser
  {{- with .Values.kafkaCluster.secret.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
type: Opaque
stringData:
  password: {{ .Values.kafkaCluster.secret.passwordConnect }}
  sasl.jaas.config: org.apache.kafka.common.security.scram.ScramLoginModule required username="{{ .Values.kafkaCluster.secret.usernameConnect }}" password="{{ .Values.kafkaCluster.secret.passwordConnect }}";
{{- end }}
